### ISSUE TITLE
Discharge the battery

### ISSUE THREAD

**Issue by esmaeil-ahmadipour** [kiwi-bop/flutter_scan_bluetooth#4]
When the search starts, the GPS activates the device. And the device charge is gradually discharged.

**Comment by nightrider77** [comment]
I also can't understand why GPS is being activated to scan BT devices

**Comment by jaumard** [comment]
> I also can't understand why GPS is being activated to scan BT devices

That's how the android API works ^^ bluetooth device can contain location positions so they ask that permission and GPS activated in order to scan BT devices... It's just how it is.

In last version of android they started adding a new API to not ask GPS permissions, but GPS is I think still used. 

Here is the doc if you want to check it out https://developer.android.com/guide/topics/connectivity/bluetooth
